name: Build Zig package
on: [push, pull_request]

jobs:
  mingw64-x64:
    name: Build Skia with MinGW Clang

    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        id: msys2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-clang mingw-w64-x86_64-lld

      - name: "Clone skia"
        run: git clone --depth 1 https://github.com/mono/skia.git skia_repo
      - name: "Build skia"
        run: |
          "${{ steps.msys2.outputs.msys2-location }}/mingw64/bin/clang" --version

          cd skia_repo
          python3 tools/git-sync-deps
          python3 bin/fetch-ninja
          bin/gn gen out/lib --args='
            target_os="win"
            target_cpu="x64"
            is_debug=false
            is_component_build=false
            is_static_skiasharp=true
            is_official_build=true
            skia_enable_fontmgr_win=true
            skia_enable_gpu=true
            skia_enable_pdf=true
            skia_use_system_libjpeg_turbo=false
            skia_use_system_libpng=false
            skia_use_system_libwebp=false
            skia_use_system_zlib=false
            skia_enable_discrete_gpu=true
            skia_use_harfbuzz=false
            skia_use_icu=false
            skia_enable_tools=false
            skia_use_expat=false
            skia_enable_skottie=false
            skia_use_gl=true
            clang_win="${{ steps.msys2.outputs.msys2-location }}/mingw64"
            clang_win_version=18
            cc="${{ steps.msys2.outputs.msys2-location }}/mingw64/bin/clang"
            cxx="${{ steps.msys2.outputs.msys2-location }}/mingw64/bin/clang++"
          '
          third_party/ninja/ninja -C out/lib skia
          
          mkdir -p ../skia/lib/win-x86_64
          cp --recursive include ../skia/include
          cp --recursive out/lib/*.lib ../skia/lib/win-x86_64/
          
          cd ..
          rm -rf skia_repo
          rm -rf .*
          ls -lah
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: "Generate zig source"
        run: sh generate.sh
      - name: Archive the build
        uses: actions/upload-artifact@v4
        with:
          name: skia-zig-package
          path: .
